server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://mysql-service:3306/reserva_vuelo
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true